
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class new_admin extends javax.swing.JFrame {
    Statement prep_statement;
    ResultSet execute_query;
    String userID;
    String admin_name;
    String admin_address, admin_phone, admin_email, admin_dob;
    /**
     * Creates new form Registration
     */
    public new_admin(String ID, String admin_name, String admin_address, String admin_phone, String admin_email, String admin_dob) {
        initComponents();
        this.userID = ID;
        this.admin_name = admin_name;
        this.admin_address = admin_address;
        this.admin_phone = admin_phone;
        this.admin_email = admin_email;
        this.admin_dob = admin_dob;
    }
    
    public Connection checkConnection() {
        db database = new db();
        Connection conn = database.checkConnection();
        return conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        logout2 = new javax.swing.JButton();
        Header_dashboard = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        Dashboard = new javax.swing.JButton();
        Courses = new javax.swing.JButton();
        Result = new javax.swing.JButton();
        teacher = new javax.swing.JButton();
        logout1 = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        Body = new javax.swing.JPanel();
        dashbaord = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        profileComponent = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_name = new javax.swing.JLabel();
        label_address = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        label_phone = new javax.swing.JLabel();
        label_dob = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        confirmpass_field = new javax.swing.JPasswordField();
        newpass_field = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        update_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        oldpass_field = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        logout2.setBackground(new java.awt.Color(75, 75, 130));
        logout2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        logout2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graduated.png"))); // NOI18N
        logout2.setText("    Student");
        logout2.setBorder(null);
        logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1054, 574));

        Header_dashboard.setBackground(new java.awt.Color(75, 75, 130));
        Header_dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Course Management System");
        Header_dashboard.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 165, 278, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentdashboard.png"))); // NOI18N
        Header_dashboard.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 18, -1, -1));

        Dashboard.setBackground(new java.awt.Color(75, 75, 130));
        Dashboard.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png"))); // NOI18N
        Dashboard.setText("Dashboard");
        Dashboard.setBorder(null);
        Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardActionPerformed(evt);
            }
        });
        Header_dashboard.add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 207, 193, 41));

        Courses.setBackground(new java.awt.Color(75, 75, 130));
        Courses.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        Courses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courses.png"))); // NOI18N
        Courses.setText("    Courses");
        Courses.setBorder(null);
        Courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoursesActionPerformed(evt);
            }
        });
        Header_dashboard.add(Courses, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 301, 193, 41));

        Result.setBackground(new java.awt.Color(75, 75, 130));
        Result.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        Result.setIcon(new javax.swing.ImageIcon(getClass().getResource("/results.png"))); // NOI18N
        Result.setText("    Result");
        Result.setBorder(null);
        Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultActionPerformed(evt);
            }
        });
        Header_dashboard.add(Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 348, 193, 41));

        teacher.setBackground(new java.awt.Color(75, 75, 130));
        teacher.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        teacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teacher.png"))); // NOI18N
        teacher.setText("    Teacher");
        teacher.setBorder(null);
        teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherActionPerformed(evt);
            }
        });
        Header_dashboard.add(teacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 395, 193, 41));

        logout1.setBackground(new java.awt.Color(75, 75, 130));
        logout1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        logout1.setText("    Logout");
        logout1.setBorder(null);
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });
        Header_dashboard.add(logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 193, 41));

        profile.setBackground(new java.awt.Color(75, 75, 130));
        profile.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        profile.setText("     Profile");
        profile.setBorder(null);
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        Header_dashboard.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 254, 193, 41));

        Body.setBackground(new java.awt.Color(255, 255, 255));
        Body.setLayout(new java.awt.CardLayout());

        dashbaord.setBackground(new java.awt.Color(255, 255, 255));
        dashbaord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Activity Log");
        dashbaord.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        jTable1.setBackground(new java.awt.Color(182, 182, 221));
        jTable1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Teacher", "Student"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        dashbaord.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        Body.add(dashbaord, "card2");

        profileComponent.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Profile");

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Id");

        label_email.setBackground(new java.awt.Color(255, 255, 255));
        label_email.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_email.setForeground(new java.awt.Color(0, 0, 0));
        label_email.setText("jLabel5");

        label_id.setBackground(new java.awt.Color(255, 255, 255));
        label_id.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_id.setForeground(new java.awt.Color(0, 0, 0));
        label_id.setText("jLabel5");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Email");

        label_name.setBackground(new java.awt.Color(255, 255, 255));
        label_name.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_name.setForeground(new java.awt.Color(0, 0, 0));
        label_name.setText("jLabel5");

        label_address.setBackground(new java.awt.Color(255, 255, 255));
        label_address.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_address.setForeground(new java.awt.Color(0, 0, 0));
        label_address.setText("jLabel5");

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Phone");

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Address");

        label_phone.setBackground(new java.awt.Color(255, 255, 255));
        label_phone.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_phone.setForeground(new java.awt.Color(0, 0, 0));
        label_phone.setText("jLabel5");

        label_dob.setBackground(new java.awt.Color(255, 255, 255));
        label_dob.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_dob.setForeground(new java.awt.Color(0, 0, 0));
        label_dob.setText("jLabel5");

        jLabel19.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("DOB");

        jLabel16.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Password");

        jLabel17.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("New Password");

        confirmpass_field.setBackground(new java.awt.Color(255, 255, 255));
        confirmpass_field.setForeground(new java.awt.Color(0, 0, 0));
        confirmpass_field.setText("jPasswordField1");

        newpass_field.setBackground(new java.awt.Color(255, 255, 255));
        newpass_field.setForeground(new java.awt.Color(0, 0, 0));
        newpass_field.setText("jPasswordField1");
        newpass_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpass_fieldActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Confirm Password");

        update_btn.setBackground(new java.awt.Color(75, 75, 130));
        update_btn.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        update_btn.setForeground(new java.awt.Color(255, 255, 255));
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N

        oldpass_field.setBackground(new java.awt.Color(255, 255, 255));
        oldpass_field.setForeground(new java.awt.Color(0, 0, 0));
        oldpass_field.setText("jPasswordField1");
        oldpass_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldpass_fieldActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Old Password");

        javax.swing.GroupLayout profileComponentLayout = new javax.swing.GroupLayout(profileComponent);
        profileComponent.setLayout(profileComponentLayout);
        profileComponentLayout.setHorizontalGroup(
            profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileComponentLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addComponent(jLabel12)
                        .addComponent(jLabel10)
                        .addComponent(jLabel6)
                        .addGroup(profileComponentLayout.createSequentialGroup()
                            .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel19))
                            .addGap(50, 50, 50)
                            .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label_dob, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                .addComponent(label_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel16)
                        .addGroup(profileComponentLayout.createSequentialGroup()
                            .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18)
                                .addComponent(jLabel20))
                            .addGap(26, 26, 26)
                            .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(newpass_field)
                                .addComponent(confirmpass_field)
                                .addComponent(oldpass_field, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                        .addComponent(jLabel4))
                    .addComponent(update_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(121, 121, 121))
        );
        profileComponentLayout.setVerticalGroup(
            profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileComponentLayout.createSequentialGroup()
                .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profileComponentLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2))
                    .addGroup(profileComponentLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(label_id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(label_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(label_address))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(label_phone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(label_email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(label_dob))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oldpass_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(newpass_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(confirmpass_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(update_btn)))
                .addGap(44, 125, Short.MAX_VALUE))
        );

        Body.add(profileComponent, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardActionPerformed
        Body.removeAll();
        Body.add(dashbaord);
        Body.repaint();
        Body.revalidate();
    }//GEN-LAST:event_DashboardActionPerformed

    private void CoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoursesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CoursesActionPerformed

    private void ResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultActionPerformed

    private void teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherActionPerformed

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
       dispose();
       Login lgn = new Login();
       lgn.setVisible(true);
        
    }//GEN-LAST:event_logout1ActionPerformed

    private void logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout2ActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        Body.removeAll();
        Body.add(profileComponent);
        Body.repaint();
        Body.revalidate();
        
        try{ 
           Connection conn = checkConnection(); 
           prep_statement = conn.createStatement();
           execute_query  = prep_statement.executeQuery("Select * from admin where id = '"+userID+"'");
           if (execute_query.next()) {
               String user_id = execute_query.getString("Id");
               String admin_name = execute_query.getString("Name");
               String admin_address = execute_query.getString("Address");
               String admin_phone = execute_query.getString("Phone");
               String admin_email = execute_query.getString("Email");
               String admin_dob = execute_query.getString("DOB");
               
               label_id.setText(user_id);
               label_name.setText(admin_name);
               label_address.setText(admin_address);
               label_phone.setText(admin_phone);
               label_email.setText(admin_email);
               label_dob.setText(admin_dob);
           } 
        }catch (Exception ex) {
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_profileActionPerformed

    private void newpass_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpass_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpass_fieldActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        try{ 
           Connection conn = checkConnection();
           prep_statement = conn.createStatement();
           String oldPass = String.valueOf(oldpass_field.getPassword());
           String newPass = String.valueOf(newpass_field.getPassword());
           String confirmPass = String.valueOf(confirmpass_field.getPassword());
           execute_query = prep_statement.executeQuery("select Id, Password from admin where id = '"+userID+"'");
           if (execute_query.next()) {
               String storePassVal = execute_query.getString("Password");
               if (oldPass.equals(storePassVal)) {
                    if (newPass.equals(confirmPass)) {
                        prep_statement.executeUpdate("update admin set Password = '"+ newPass +"' where Id = '"+userID+"'");
                        JOptionPane.showMessageDialog(this, "Password Updated Sucessfully");
                        return;
                    } else {
                        JOptionPane.showMessageDialog(this, "Password does not match!");
                        return;
                    }
               } else {
                   JOptionPane.showMessageDialog(this, "Old password does not match!");
                   return;
               }
           }
        }catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_update_btnActionPerformed

    private void oldpass_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldpass_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldpass_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_admin("null", "null", "null", "null", "null", "null").setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JButton Courses;
    private javax.swing.JButton Dashboard;
    private javax.swing.JPanel Header_dashboard;
    private javax.swing.JButton Result;
    private javax.swing.JPasswordField confirmpass_field;
    private javax.swing.JPanel dashbaord;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private javax.swing.JLabel label_address;
    private javax.swing.JLabel label_dob;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_phone;
    private javax.swing.JButton logout1;
    private javax.swing.JButton logout2;
    private javax.swing.JPasswordField newpass_field;
    private javax.swing.JPasswordField oldpass_field;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JButton profile;
    private javax.swing.JPanel profileComponent;
    private javax.swing.JButton teacher;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
