
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class new_admin extends javax.swing.JFrame {
    Statement prep_statement;
    PreparedStatement prep_state;
    ResultSet execute_query;
    String userID;
    String admin_name;
    String admin_address, admin_phone, admin_email, admin_dob;
    /**
     * Creates new form Registration
     */
    public new_admin(String ID, String admin_name, String admin_address, String admin_phone, String admin_email, String admin_dob) {
        initComponents();
        this.userID = ID;
        this.admin_name = admin_name;
        this.admin_address = admin_address;
        this.admin_phone = admin_phone;
        this.admin_email = admin_email;
        this.admin_dob = admin_dob;
    }
    
    public Connection checkConnection() {
        db database = new db();
        Connection conn = database.checkConnection();
        return conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header_dashboard = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        Dashboard = new javax.swing.JButton();
        Courses = new javax.swing.JButton();
        Result = new javax.swing.JButton();
        teacher = new javax.swing.JButton();
        logout1 = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        Body = new javax.swing.JPanel();
        dashbaord = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        profileComponent = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_name = new javax.swing.JLabel();
        label_address = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        label_phone = new javax.swing.JLabel();
        label_dob = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        confirmpass_field = new javax.swing.JPasswordField();
        newpass_field = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        update_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        oldpass_field = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        coursesComponent = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        login_btn1 = new javax.swing.JButton();
        login_btn2 = new javax.swing.JButton();
        add_courses_btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        addCoursesComponent = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        course_name_label = new javax.swing.JTextField();
        Back_btn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        year_label = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        sem_label = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        module1_label = new javax.swing.JTextField();
        module2_label = new javax.swing.JTextField();
        module3A_label = new javax.swing.JTextField();
        module4A_label = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        module3B_label = new javax.swing.JTextField();
        module4B_label = new javax.swing.JTextField();
        add_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1054, 574));

        Header_dashboard.setBackground(new java.awt.Color(75, 75, 130));
        Header_dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Course Management System");
        Header_dashboard.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 165, 278, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentdashboard.png"))); // NOI18N
        Header_dashboard.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 18, -1, -1));

        Dashboard.setBackground(new java.awt.Color(75, 75, 130));
        Dashboard.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png"))); // NOI18N
        Dashboard.setText("Dashboard");
        Dashboard.setBorder(null);
        Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardActionPerformed(evt);
            }
        });
        Header_dashboard.add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 207, 193, 41));

        Courses.setBackground(new java.awt.Color(75, 75, 130));
        Courses.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        Courses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courses.png"))); // NOI18N
        Courses.setText("    Courses");
        Courses.setBorder(null);
        Courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoursesActionPerformed(evt);
            }
        });
        Header_dashboard.add(Courses, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 301, 193, 41));

        Result.setBackground(new java.awt.Color(75, 75, 130));
        Result.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        Result.setIcon(new javax.swing.ImageIcon(getClass().getResource("/results.png"))); // NOI18N
        Result.setText("    Result");
        Result.setBorder(null);
        Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultActionPerformed(evt);
            }
        });
        Header_dashboard.add(Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 348, 193, 41));

        teacher.setBackground(new java.awt.Color(75, 75, 130));
        teacher.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        teacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teacher.png"))); // NOI18N
        teacher.setText("    Teacher");
        teacher.setBorder(null);
        teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherActionPerformed(evt);
            }
        });
        Header_dashboard.add(teacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 395, 193, 41));

        logout1.setBackground(new java.awt.Color(75, 75, 130));
        logout1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        logout1.setText("    Logout");
        logout1.setBorder(null);
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });
        Header_dashboard.add(logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 193, 41));

        profile.setBackground(new java.awt.Color(75, 75, 130));
        profile.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        profile.setText("     Profile");
        profile.setBorder(null);
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        Header_dashboard.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 254, 193, 41));

        Body.setBackground(new java.awt.Color(255, 255, 255));
        Body.setLayout(new java.awt.CardLayout());

        dashbaord.setBackground(new java.awt.Color(255, 255, 255));
        dashbaord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Activity Log");
        dashbaord.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        jTable1.setBackground(new java.awt.Color(182, 182, 221));
        jTable1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Teacher", "Student"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        dashbaord.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        Body.add(dashbaord, "card2");

        profileComponent.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Profile");

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Id");

        label_email.setBackground(new java.awt.Color(255, 255, 255));
        label_email.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_email.setForeground(new java.awt.Color(0, 0, 0));
        label_email.setText("jLabel5");

        label_id.setBackground(new java.awt.Color(255, 255, 255));
        label_id.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_id.setForeground(new java.awt.Color(0, 0, 0));
        label_id.setText("jLabel5");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Email");

        label_name.setBackground(new java.awt.Color(255, 255, 255));
        label_name.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_name.setForeground(new java.awt.Color(0, 0, 0));
        label_name.setText("jLabel5");

        label_address.setBackground(new java.awt.Color(255, 255, 255));
        label_address.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_address.setForeground(new java.awt.Color(0, 0, 0));
        label_address.setText("jLabel5");

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Phone");

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Address");

        label_phone.setBackground(new java.awt.Color(255, 255, 255));
        label_phone.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_phone.setForeground(new java.awt.Color(0, 0, 0));
        label_phone.setText("jLabel5");

        label_dob.setBackground(new java.awt.Color(255, 255, 255));
        label_dob.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_dob.setForeground(new java.awt.Color(0, 0, 0));
        label_dob.setText("jLabel5");

        jLabel19.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("DOB");

        jLabel16.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Password");

        jLabel17.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("New Password");

        confirmpass_field.setBackground(new java.awt.Color(255, 255, 255));
        confirmpass_field.setForeground(new java.awt.Color(0, 0, 0));
        confirmpass_field.setText("jPasswordField1");

        newpass_field.setBackground(new java.awt.Color(255, 255, 255));
        newpass_field.setForeground(new java.awt.Color(0, 0, 0));
        newpass_field.setText("jPasswordField1");
        newpass_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpass_fieldActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Confirm Password");

        update_btn.setBackground(new java.awt.Color(75, 75, 130));
        update_btn.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        update_btn.setForeground(new java.awt.Color(255, 255, 255));
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N

        oldpass_field.setBackground(new java.awt.Color(255, 255, 255));
        oldpass_field.setForeground(new java.awt.Color(0, 0, 0));
        oldpass_field.setText("jPasswordField1");
        oldpass_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldpass_fieldActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Old Password");

        javax.swing.GroupLayout profileComponentLayout = new javax.swing.GroupLayout(profileComponent);
        profileComponent.setLayout(profileComponentLayout);
        profileComponentLayout.setHorizontalGroup(
            profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileComponentLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addComponent(jLabel12)
                        .addComponent(jLabel10)
                        .addComponent(jLabel6)
                        .addGroup(profileComponentLayout.createSequentialGroup()
                            .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel19))
                            .addGap(50, 50, 50)
                            .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label_dob, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                .addComponent(label_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel16)
                        .addGroup(profileComponentLayout.createSequentialGroup()
                            .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18)
                                .addComponent(jLabel20))
                            .addGap(26, 26, 26)
                            .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(newpass_field)
                                .addComponent(confirmpass_field)
                                .addComponent(oldpass_field, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                        .addComponent(jLabel4))
                    .addComponent(update_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(121, 121, 121))
        );
        profileComponentLayout.setVerticalGroup(
            profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileComponentLayout.createSequentialGroup()
                .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profileComponentLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2))
                    .addGroup(profileComponentLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(label_id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(label_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(label_address))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(label_phone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(label_email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(label_dob))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oldpass_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(newpass_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(confirmpass_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(update_btn)))
                .addGap(44, 125, Short.MAX_VALUE))
        );

        Body.add(profileComponent, "card2");

        coursesComponent.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Courses");

        login_btn1.setBackground(new java.awt.Color(75, 75, 130));
        login_btn1.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        login_btn1.setForeground(new java.awt.Color(255, 255, 255));
        login_btn1.setText("Active Courses");
        login_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btn1ActionPerformed(evt);
            }
        });

        login_btn2.setBackground(new java.awt.Color(75, 75, 130));
        login_btn2.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        login_btn2.setForeground(new java.awt.Color(255, 255, 255));
        login_btn2.setText("Deactivated Courses");
        login_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btn2ActionPerformed(evt);
            }
        });

        add_courses_btn.setBackground(new java.awt.Color(75, 75, 130));
        add_courses_btn.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        add_courses_btn.setForeground(new java.awt.Color(255, 255, 255));
        add_courses_btn.setText("Add Courses");
        add_courses_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_courses_btnActionPerformed(evt);
            }
        });

        jList1.setBackground(new java.awt.Color(204, 204, 255));
        jList1.setForeground(new java.awt.Color(0, 0, 0));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Ongoing Courses");

        javax.swing.GroupLayout coursesComponentLayout = new javax.swing.GroupLayout(coursesComponent);
        coursesComponent.setLayout(coursesComponentLayout);
        coursesComponentLayout.setHorizontalGroup(
            coursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursesComponentLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(coursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(coursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)
                        .addGroup(coursesComponentLayout.createSequentialGroup()
                            .addComponent(login_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(login_btn2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(add_courses_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(coursesComponentLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(399, 399, 399)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        coursesComponentLayout.setVerticalGroup(
            coursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursesComponentLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(coursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_courses_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        Body.add(coursesComponent, "card2");

        addCoursesComponent.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Add Courses");

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Course Name");

        course_name_label.setBackground(new java.awt.Color(255, 255, 255));
        course_name_label.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        course_name_label.setForeground(new java.awt.Color(0, 0, 0));

        Back_btn.setBackground(new java.awt.Color(255, 255, 255));
        Back_btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow.png"))); // NOI18N
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Year ");

        year_label.setBackground(new java.awt.Color(255, 255, 255));
        year_label.setForeground(new java.awt.Color(0, 0, 0));
        year_label.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year 1", "Year 2", "Year 3" }));
        year_label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year_labelActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Semester");

        sem_label.setBackground(new java.awt.Color(255, 255, 255));
        sem_label.setForeground(new java.awt.Color(0, 0, 0));
        sem_label.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem 1", "Sem 2" }));
        sem_label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem_labelActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Module 1");

        module1_label.setBackground(new java.awt.Color(255, 255, 255));
        module1_label.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        module1_label.setForeground(new java.awt.Color(0, 0, 0));

        module2_label.setBackground(new java.awt.Color(255, 255, 255));
        module2_label.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        module2_label.setForeground(new java.awt.Color(0, 0, 0));

        module3A_label.setBackground(new java.awt.Color(255, 255, 255));
        module3A_label.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        module3A_label.setForeground(new java.awt.Color(0, 0, 0));

        module4A_label.setBackground(new java.awt.Color(255, 255, 255));
        module4A_label.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        module4A_label.setForeground(new java.awt.Color(0, 0, 0));
        module4A_label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                module4A_labelActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Module 2");

        jLabel24.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Module 3");

        jLabel25.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Module 4");

        module3B_label.setBackground(new java.awt.Color(255, 255, 255));
        module3B_label.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        module3B_label.setForeground(new java.awt.Color(0, 0, 0));

        module4B_label.setBackground(new java.awt.Color(255, 255, 255));
        module4B_label.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        module4B_label.setForeground(new java.awt.Color(0, 0, 0));
        module4B_label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                module4B_labelActionPerformed(evt);
            }
        });

        add_btn.setBackground(new java.awt.Color(75, 75, 130));
        add_btn.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        add_btn.setForeground(new java.awt.Color(255, 255, 255));
        add_btn.setText("Add");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addCoursesComponentLayout = new javax.swing.GroupLayout(addCoursesComponent);
        addCoursesComponent.setLayout(addCoursesComponentLayout);
        addCoursesComponentLayout.setHorizontalGroup(
            addCoursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCoursesComponentLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(addCoursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCoursesComponentLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Back_btn)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCoursesComponentLayout.createSequentialGroup()
                        .addGroup(addCoursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(addCoursesComponentLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(39, 39, 39)
                                .addComponent(course_name_label))
                            .addGroup(addCoursesComponentLayout.createSequentialGroup()
                                .addGroup(addCoursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addGap(75, 75, 75)
                                .addGroup(addCoursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(module1_label, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(module2_label, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(module3A_label)
                                    .addComponent(module3B_label)
                                    .addComponent(module4A_label)
                                    .addComponent(module4B_label)
                                    .addGroup(addCoursesComponentLayout.createSequentialGroup()
                                        .addComponent(year_label, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                        .addComponent(sem_label, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(addCoursesComponentLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(264, 264, 264))))
        );
        addCoursesComponentLayout.setVerticalGroup(
            addCoursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCoursesComponentLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(addCoursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(Back_btn))
                .addGap(18, 18, 18)
                .addGroup(addCoursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(course_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(addCoursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCoursesComponentLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21))
                    .addGroup(addCoursesComponentLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(addCoursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(year_label, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(sem_label, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addCoursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(module1_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addCoursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(module2_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addCoursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(module3A_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(8, 8, 8)
                .addComponent(module3B_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCoursesComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(module4A_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(module4B_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        Body.add(addCoursesComponent, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardActionPerformed
        Body.removeAll();
        Body.add(dashbaord);
        Body.repaint();
        Body.revalidate();
    }//GEN-LAST:event_DashboardActionPerformed

    private void CoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoursesActionPerformed
        Body.removeAll();
        Body.add(coursesComponent);
        Body.repaint();
        Body.revalidate();
    }//GEN-LAST:event_CoursesActionPerformed

    private void ResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultActionPerformed

    private void teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherActionPerformed

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
       dispose();
       Login lgn = new Login();
       lgn.setVisible(true);
        
    }//GEN-LAST:event_logout1ActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        Body.removeAll();
        Body.add(profileComponent);
        Body.repaint();
        Body.revalidate();
        
        try{ 
           Connection conn = checkConnection(); 
           prep_statement = conn.createStatement();
           execute_query  = prep_statement.executeQuery("Select * from admin where id = '"+userID+"'");
           if (execute_query.next()) {
               String user_id = execute_query.getString("Id");
               String admin_name = execute_query.getString("Name");
               String admin_address = execute_query.getString("Address");
               String admin_phone = execute_query.getString("Phone");
               String admin_email = execute_query.getString("Email");
               String admin_dob = execute_query.getString("DOB");
               
               label_id.setText(user_id);
               label_name.setText(admin_name);
               label_address.setText(admin_address);
               label_phone.setText(admin_phone);
               label_email.setText(admin_email);
               label_dob.setText(admin_dob);
           } 
        }catch (Exception ex) {
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_profileActionPerformed

    private void newpass_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpass_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpass_fieldActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        try{ 
           Connection conn = checkConnection();
           prep_statement = conn.createStatement();
           String oldPass = String.valueOf(oldpass_field.getPassword());
           String newPass = String.valueOf(newpass_field.getPassword());
           String confirmPass = String.valueOf(confirmpass_field.getPassword());
           execute_query = prep_statement.executeQuery("select Id, Password from admin where id = '"+userID+"'");
           if (execute_query.next()) {
               String storePassVal = execute_query.getString("Password");
               if (oldPass.equals(storePassVal)) {
                    if (newPass.equals(confirmPass)) {
                        prep_statement.executeUpdate("update admin set Password = '"+ newPass +"' where Id = '"+userID+"'");
                        JOptionPane.showMessageDialog(this, "Password Updated Sucessfully");
                        return;
                    } else {
                        JOptionPane.showMessageDialog(this, "Password does not match!");
                        return;
                    }
               } else {
                   JOptionPane.showMessageDialog(this, "Old password does not match!");
                   return;
               }
           }
        }catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_update_btnActionPerformed

    private void oldpass_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldpass_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldpass_fieldActionPerformed

    private void login_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btn1ActionPerformed

    private void login_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btn2ActionPerformed

    private void add_courses_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_courses_btnActionPerformed
        Body.removeAll();
        Body.add(addCoursesComponent);
        Body.repaint();
        Body.revalidate();
    }//GEN-LAST:event_add_courses_btnActionPerformed

    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        Body.removeAll();
        Body.add(coursesComponent);
        Body.repaint();
        Body.revalidate();
    }//GEN-LAST:event_Back_btnActionPerformed

    private void module4A_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_module4A_labelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_module4A_labelActionPerformed

    private void module4B_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_module4B_labelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_module4B_labelActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        try {
            Connection conn = checkConnection();
            String course_name = course_name_label.getText();
            String year = year_label.getSelectedItem().toString();
            String sem = sem_label.getSelectedItem().toString();
            String module1 = module1_label.getText();
            String module2 = module2_label.getText();
            String module3A = module3A_label.getText();
            String module3B = module3B_label.getText();
            String module4A = module4A_label.getText();
            String module4B = module4B_label.getText();
            
            if (year == "Year 3"){
                if (course_name.isEmpty() ||  sem.isEmpty()|| module1.isEmpty() || module2.isEmpty() || module3A.isEmpty()|| module3B.isEmpty() || module4A.isEmpty() || module4B.isEmpty() ) {
                        JOptionPane.showMessageDialog(this, "Do not leave any field Empty.");
                        return;
                }
            } else {
                if (course_name.isEmpty() || sem.isEmpty()|| module1.isEmpty() || module2.isEmpty() || module3A.isEmpty()|| module4A.isEmpty() ) {
                        JOptionPane.showMessageDialog(this, "Do not leave any field Empty.");
                        return;
                }
            }
            
            prep_state  = conn.prepareStatement("Insert into courses(CourseName) values ('"+course_name+"')");
            int row = prep_state.executeUpdate();
            System.out.println(row);
            
            if (year == "Year 1") {
                prep_state  = conn.prepareStatement("Insert into year1(sem, module_1, module_2, module_3, module_4) values (?, ?, ?, ?, ?)");
                prep_state.setString(1, sem);
                prep_state.setString(2, module1);
                prep_state.setString(3, module2);
                prep_state.setString(4, module3A);
                prep_state.setString(5, module4B);
                
                row = prep_state.executeUpdate();
                System.out.println(row);
                
                JOptionPane.showMessageDialog(this, "Course Added Successfully.");
                
                Body.removeAll();
                Body.add(coursesComponent);
                Body.repaint();
                Body.revalidate();
                return;
                
            } else if (year == "Year 2") {
                prep_state  = conn.prepareStatement("Insert into year2(sem, module_1, module_2, module_3, module_4) values (?, ?, ?, ?, ?)");
                prep_state.setString(1, sem);
                prep_state.setString(2, module1);
                prep_state.setString(3, module2);
                prep_state.setString(4, module3A);
                prep_state.setString(5, module4B);
                
                row = prep_state.executeUpdate();
                System.out.println(row);
                
                JOptionPane.showMessageDialog(this, "Course Added Successfully.");
                
                Body.removeAll();
                Body.add(coursesComponent);
                Body.repaint();
                Body.revalidate();
                return;
                
            } else if (year == "Year 3") {
                prep_state  = conn.prepareStatement("Insert into year3(sem, module_1, module_2, module_3A, moudle_3B, module_4A, module_4B) values (?, ?, ?, ?, ?, ?, ?)");
                prep_state.setString(1, sem);
                prep_state.setString(2, module1);
                prep_state.setString(3, module2);
                prep_state.setString(4, module3A);
                prep_state.setString(5, module3B);
                prep_state.setString(6, module4A);
                prep_state.setString(7, module4B);
                
                row = prep_state.executeUpdate();
                System.out.println(row);
                
                JOptionPane.showMessageDialog(this, "Course Added Successfully.");
                
                Body.removeAll();
                Body.add(coursesComponent);
                Body.repaint();
                Body.revalidate();
                return;
                
            }
            
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_add_btnActionPerformed

    private void sem_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem_labelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sem_labelActionPerformed

    private void year_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year_labelActionPerformed
        String year = year_label.getSelectedItem().toString();
        
        if(year == "Year 3") {
            module3B_label.setVisible(true);
            module4B_label.setVisible(true);
        } else {
            module3B_label.setVisible(false);
            module4B_label.setVisible(false);
        }
    }//GEN-LAST:event_year_labelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_admin("null", "null", "null", "null", "null", "null").setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JPanel Body;
    private javax.swing.JButton Courses;
    private javax.swing.JButton Dashboard;
    private javax.swing.JPanel Header_dashboard;
    private javax.swing.JButton Result;
    private javax.swing.JPanel addCoursesComponent;
    private javax.swing.JButton add_btn;
    private javax.swing.JButton add_courses_btn;
    private javax.swing.JPasswordField confirmpass_field;
    private javax.swing.JTextField course_name_label;
    private javax.swing.JPanel coursesComponent;
    private javax.swing.JPanel dashbaord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private javax.swing.JLabel label_address;
    private javax.swing.JLabel label_dob;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_phone;
    private javax.swing.JButton login_btn1;
    private javax.swing.JButton login_btn2;
    private javax.swing.JButton logout1;
    private javax.swing.JTextField module1_label;
    private javax.swing.JTextField module2_label;
    private javax.swing.JTextField module3A_label;
    private javax.swing.JTextField module3B_label;
    private javax.swing.JTextField module4A_label;
    private javax.swing.JTextField module4B_label;
    private javax.swing.JPasswordField newpass_field;
    private javax.swing.JPasswordField oldpass_field;
    private javax.swing.JButton profile;
    private javax.swing.JPanel profileComponent;
    private javax.swing.JComboBox<String> sem_label;
    private javax.swing.JButton teacher;
    private javax.swing.JButton update_btn;
    private javax.swing.JComboBox<String> year_label;
    // End of variables declaration//GEN-END:variables
}
