/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
import java.util.regex.Pattern;
import java.sql.*;
import javax.swing.JOptionPane;

public class Registration_pg extends javax.swing.JFrame {
    Statement prep;
    PreparedStatement prep_statement;
    ResultSet execute_query;
    /**
     * Creates new form Registration
     */
    public Registration_pg() {
        initComponents();
        fetchCombobox();
    }
    
    
    public void fetchCombobox() {
        try{
         Connection conn = checkConnection();
         Statement prep_statement = conn.createStatement();
         execute_query = prep_statement.executeQuery("select * from courses where Status = 'Active'");

            
            while (execute_query.next()) {
                String tempVar2 = execute_query.getString("CourseName");
                courseCombo.addItem(tempVar2);
            }
        } catch (Exception exp) {
            System.out.println(exp);
        }
    }
    
    public Connection checkConnection() {
        db database = new db();
        Connection conn = database.checkConnection();
        return conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        body_login = new javax.swing.JPanel();
        header_login = new javax.swing.JPanel();
        login_btn_register = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        First_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        Last_name = new javax.swing.JTextField();
        Middle_name = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        course_label = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        courseCombo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        confirm_password = new javax.swing.JPasswordField();
        submit_btn = new javax.swing.JButton();
        Cancel_btn = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        body_login.setBackground(new java.awt.Color(255, 255, 255));

        header_login.setBackground(new java.awt.Color(75, 75, 130));

        login_btn_register.setBackground(new java.awt.Color(255, 255, 255));
        login_btn_register.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        login_btn_register.setForeground(new java.awt.Color(75, 75, 130));
        login_btn_register.setText("Login");
        login_btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btn_registerActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Don't have an account?");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("SimSun", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CMS");

        javax.swing.GroupLayout header_loginLayout = new javax.swing.GroupLayout(header_login);
        header_login.setLayout(header_loginLayout);
        header_loginLayout.setHorizontalGroup(
            header_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_loginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        header_loginLayout.setVerticalGroup(
            header_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(header_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(75, 75, 130));
        jLabel1.setText("Registration");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Name");

        First_name.setBackground(new java.awt.Color(255, 255, 255));
        First_name.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        First_name.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("First Name");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Middle Name");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Last Name");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("DOB");

        dob.setBackground(new java.awt.Color(255, 255, 255));
        dob.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        dob.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Address");

        address.setBackground(new java.awt.Color(255, 255, 255));
        address.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        address.setForeground(new java.awt.Color(0, 0, 0));

        Last_name.setBackground(new java.awt.Color(255, 255, 255));
        Last_name.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Last_name.setForeground(new java.awt.Color(0, 0, 0));

        Middle_name.setBackground(new java.awt.Color(255, 255, 255));
        Middle_name.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Middle_name.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Gender");

        gender.setBackground(new java.awt.Color(255, 255, 255));
        gender.setForeground(new java.awt.Color(0, 0, 0));
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Email");

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 0));

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Phone");

        phone.setBackground(new java.awt.Color(255, 255, 255));
        phone.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        phone.setForeground(new java.awt.Color(0, 0, 0));

        course_label.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        course_label.setForeground(new java.awt.Color(0, 0, 0));
        course_label.setText("Course");

        jLabel16.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Role");

        role.setBackground(new java.awt.Color(255, 255, 255));
        role.setForeground(new java.awt.Color(0, 0, 0));
        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Teacher" }));
        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });

        courseCombo.setBackground(new java.awt.Color(255, 255, 255));
        courseCombo.setForeground(new java.awt.Color(0, 0, 0));
        courseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Password");

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(0, 0, 0));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Confirm Password");

        confirm_password.setBackground(new java.awt.Color(255, 255, 255));
        confirm_password.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        confirm_password.setForeground(new java.awt.Color(0, 0, 0));
        confirm_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_passwordActionPerformed(evt);
            }
        });

        submit_btn.setBackground(new java.awt.Color(75, 75, 130));
        submit_btn.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        submit_btn.setText("Submit");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        Cancel_btn.setBackground(new java.awt.Color(75, 75, 130));
        Cancel_btn.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        Cancel_btn.setForeground(new java.awt.Color(255, 255, 255));
        Cancel_btn.setText("Cancel");
        Cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout body_loginLayout = new javax.swing.GroupLayout(body_login);
        body_login.setLayout(body_loginLayout);
        body_loginLayout.setHorizontalGroup(
            body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(body_loginLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(body_loginLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body_loginLayout.createSequentialGroup()
                        .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(body_loginLayout.createSequentialGroup()
                                .addComponent(course_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(33, 33, 33))
                            .addGroup(body_loginLayout.createSequentialGroup()
                                .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel8))
                                    .addComponent(jLabel14))
                                .addGap(39, 39, 39)))
                        .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(body_loginLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(236, 236, 236)
                                .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(Middle_name, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body_loginLayout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body_loginLayout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(body_loginLayout.createSequentialGroup()
                                            .addComponent(Cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(body_loginLayout.createSequentialGroup()
                                .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(dob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(First_name, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(courseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(body_loginLayout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(body_loginLayout.createSequentialGroup()
                                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(body_loginLayout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(244, 244, 244))
                                    .addGroup(body_loginLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(450, 450, 450))
        );
        body_loginLayout.setVerticalGroup(
            body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body_loginLayout.createSequentialGroup()
                .addComponent(header_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(First_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Middle_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course_label))
                .addGap(18, 18, 18)
                .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(body_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btn_registerActionPerformed
       dispose();
       Login lgn = new Login();
       lgn.setVisible(true);
    }//GEN-LAST:event_login_btn_registerActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void confirm_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm_passwordActionPerformed

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
       try{ 
           Connection conn = checkConnection(); 
           
           String first_name = First_name.getText();
           String middle_name = Middle_name.getText();
           String last_name = Last_name.getText();
           String DOB = dob.getText();
           String Address = address.getText();
           String Gender =  gender.getSelectedItem().toString();
           String Phone = phone.getText();
           String phone_regex = "([0-9]).{9}$";
           String Email = email.getText();
           String email_regex = "^[\\S]+@(heraldcollege\\.edu\\.np)$";
           String Role = role.getSelectedItem().toString();
           String Course = courseCombo.getSelectedItem().toString();
           String Password =  String.valueOf(password.getPassword());
           String Confirm_password = String.valueOf(confirm_password.getPassword());
           
           
           
           if (first_name.isEmpty() || last_name.isEmpty() || DOB.isEmpty() || Address.isEmpty() || Gender.isEmpty() || Phone.isEmpty() || Email.isEmpty() || Role.isEmpty() || Course.isEmpty() || Password.isEmpty()) {
               JOptionPane.showMessageDialog(this, "Do not leave any field empty");
               return;
            }
           
           if (!Pattern.matches(phone_regex, Phone)) {
                JOptionPane.showMessageDialog(this, "Phone number must be 10 digits!");
                return;
            }
           
           if (!Pattern.matches(email_regex, Email)) {
                JOptionPane.showMessageDialog(this, "Please use the email provided by the college!", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
           
           if (!Password.equals(Confirm_password)) {
               JOptionPane.showMessageDialog(this, "Password not matched");
               return;
           }
           
           
           
           
           
           if (Role == "Student") {
               prep = conn.createStatement();
               execute_query = prep.executeQuery("Select * from student where Email = '"+Email+"' or Phone = '"+Phone+"'");
                
                if(execute_query.next()) {
                    JOptionPane.showMessageDialog(this, "Email or Phone Number already in use.");
                    return;
                }
                prep_statement = conn.prepareStatement("Insert into student (First_Name, Middle_Name, Last_Name, DOB, Address, Gender, Phone, Email, Course, Password, Year_1) values (?, ?, ?, ?, ?, ?, ?, ?, ?,?,?)");
                prep_statement.setString(1, first_name);
                prep_statement.setString(2, middle_name);
                prep_statement.setString(3, last_name);
                prep_statement.setString(4, DOB);
                prep_statement.setString(5, Address);
                prep_statement.setString(6, Gender);
                prep_statement.setString(7, Phone);
                prep_statement.setString(8, Email);
                prep_statement.setString(9, Course);
                prep_statement.setString(10, Password);
                prep_statement.setString(11, "No");
               
                int row = prep_statement.executeUpdate();
                System.out.println(row);
                JOptionPane.showMessageDialog(this, "Registration Successful");
                dispose();
                Login lgn = new Login();
                lgn.setVisible(true);
                return;
           } else if  (Role == "Teacher") {
               prep = conn.createStatement();
               execute_query = prep.executeQuery("Select * from teacher where Email = '"+Email+"' or Phone = '"+Phone+"'");
                
                if(execute_query.next()) {
                    JOptionPane.showMessageDialog(this, "Email or Phone Number already in use.");
                    return;
                }
                prep_statement = conn.prepareStatement("Insert into teacher (First_Name, Middle_Name, Last_Name, DOB, Address, Gender, Phone, Email, Password) values (?, ?, ?, ?, ?, ?, ?, ?, ?)");
                prep_statement.setString(1, first_name);
                prep_statement.setString(2, middle_name);
                prep_statement.setString(3, last_name);
                prep_statement.setString(4, DOB);
                prep_statement.setString(5, Address);
                prep_statement.setString(6, Gender);
                prep_statement.setString(7, Phone);
                prep_statement.setString(8, Email);
                prep_statement.setString(9, Password);
                int row = prep_statement.executeUpdate();
                System.out.println(row);
                JOptionPane.showMessageDialog(this, "Registration Successful");
                dispose();
                Login lgn = new Login();
                lgn.setVisible(true);
                return;
           }

        }catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_submit_btnActionPerformed

    private void Cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_btnActionPerformed
       dispose();
       Login lgn = new Login();
       lgn.setVisible(true);
    }//GEN-LAST:event_Cancel_btnActionPerformed

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        String isRole = role.getSelectedItem().toString();
        if (isRole != "Student") {
            courseCombo.setVisible(false);
            course_label.setVisible(false);
        } else {
            courseCombo.setVisible(true);
            course_label.setVisible(true);
        }
    }//GEN-LAST:event_roleActionPerformed

    private void courseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboActionPerformed
        
                  

    }//GEN-LAST:event_courseComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration_pg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel_btn;
    private javax.swing.JTextField First_name;
    private javax.swing.JTextField Last_name;
    private javax.swing.JTextField Middle_name;
    private javax.swing.JTextField address;
    private javax.swing.JPanel body_login;
    private javax.swing.JPasswordField confirm_password;
    private javax.swing.JComboBox<String> courseCombo;
    private javax.swing.JLabel course_label;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JPanel header_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton login_btn_register;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JButton submit_btn;
    // End of variables declaration//GEN-END:variables
}
