/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */

import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Student_portal extends javax.swing.JFrame {
    Statement prep_statement;
   PreparedStatement prep;
    ResultSet execute_query;
    String student_id;
    /**
     * Creates new form Registration
     */
    public Student_portal(String student_id) {
        initComponents();
        this.student_id = student_id;
    }
    
    public Connection checkConnection() {
        db database = new db();
        Connection conn = database.checkConnection();
        return conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        header = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        Result = new javax.swing.JButton();
        teacher = new javax.swing.JButton();
        logout1 = new javax.swing.JButton();
        Body = new javax.swing.JPanel();
        profileComponent = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        label_student_email = new javax.swing.JLabel();
        label_student_id = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_student_name = new javax.swing.JLabel();
        label_student_address = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        label_student_phone = new javax.swing.JLabel();
        label_student_dob = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        student_confirmpass_field = new javax.swing.JPasswordField();
        student_newpass_field = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        update_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        student_oldpass_field = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        label_student_course = new javax.swing.JLabel();
        YearWiseModule = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Enrolled_Btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        enrolled_modules = new javax.swing.JTable();
        year1_component = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        module1 = new javax.swing.JComboBox<>();
        module2 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        module3 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        module4 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        update_btn1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        year_label = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        sem_label = new javax.swing.JComboBox<>();
        teacher_components = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        teacher_list_table = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1054, 574));

        header.setBackground(new java.awt.Color(75, 75, 130));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Course Management System");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentdashboard.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(75, 75, 130));
        jButton1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png"))); // NOI18N
        jButton1.setText("Dashboard");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(75, 75, 130));
        jButton2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cubes.png"))); // NOI18N
        jButton2.setText("    Module");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        profile.setBackground(new java.awt.Color(75, 75, 130));
        profile.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        profile.setText("     Profile");
        profile.setBorder(null);
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });

        Result.setBackground(new java.awt.Color(75, 75, 130));
        Result.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        Result.setIcon(new javax.swing.ImageIcon(getClass().getResource("/results.png"))); // NOI18N
        Result.setText("    Result");
        Result.setBorder(null);
        Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultActionPerformed(evt);
            }
        });

        teacher.setBackground(new java.awt.Color(75, 75, 130));
        teacher.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        teacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teacher.png"))); // NOI18N
        teacher.setText("    Teacher");
        teacher.setBorder(null);
        teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherActionPerformed(evt);
            }
        });

        logout1.setBackground(new java.awt.Color(75, 75, 130));
        logout1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        logout1.setText("    Logout");
        logout1.setBorder(null);
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(headerLayout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Body.setBackground(new java.awt.Color(255, 255, 255));
        Body.setLayout(new java.awt.CardLayout());

        profileComponent.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Profile");

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Id");

        label_student_email.setBackground(new java.awt.Color(255, 255, 255));
        label_student_email.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_student_email.setForeground(new java.awt.Color(0, 0, 0));
        label_student_email.setText("jLabel5");

        label_student_id.setBackground(new java.awt.Color(255, 255, 255));
        label_student_id.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_student_id.setForeground(new java.awt.Color(0, 0, 0));
        label_student_id.setText("jLabel5");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Email");

        label_student_name.setBackground(new java.awt.Color(255, 255, 255));
        label_student_name.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_student_name.setForeground(new java.awt.Color(0, 0, 0));
        label_student_name.setText("jLabel5");

        label_student_address.setBackground(new java.awt.Color(255, 255, 255));
        label_student_address.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_student_address.setForeground(new java.awt.Color(0, 0, 0));
        label_student_address.setText("jLabel5");

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Phone");

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Address");

        label_student_phone.setBackground(new java.awt.Color(255, 255, 255));
        label_student_phone.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_student_phone.setForeground(new java.awt.Color(0, 0, 0));
        label_student_phone.setText("jLabel5");

        label_student_dob.setBackground(new java.awt.Color(255, 255, 255));
        label_student_dob.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_student_dob.setForeground(new java.awt.Color(0, 0, 0));
        label_student_dob.setText("jLabel5");

        jLabel19.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("DOB");

        jLabel16.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Password");

        jLabel17.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("New Password");

        student_confirmpass_field.setBackground(new java.awt.Color(255, 255, 255));
        student_confirmpass_field.setForeground(new java.awt.Color(0, 0, 0));
        student_confirmpass_field.setText("jPasswordField1");

        student_newpass_field.setBackground(new java.awt.Color(255, 255, 255));
        student_newpass_field.setForeground(new java.awt.Color(0, 0, 0));
        student_newpass_field.setText("jPasswordField1");
        student_newpass_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_newpass_fieldActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Confirm Password");

        update_btn.setBackground(new java.awt.Color(75, 75, 130));
        update_btn.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        update_btn.setForeground(new java.awt.Color(255, 255, 255));
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N

        student_oldpass_field.setBackground(new java.awt.Color(255, 255, 255));
        student_oldpass_field.setForeground(new java.awt.Color(0, 0, 0));
        student_oldpass_field.setText("jPasswordField1");
        student_oldpass_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_oldpass_fieldActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Old Password");

        jLabel21.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Courses");

        label_student_course.setBackground(new java.awt.Color(255, 255, 255));
        label_student_course.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_student_course.setForeground(new java.awt.Color(0, 0, 0));
        label_student_course.setText("jLabel5");

        javax.swing.GroupLayout profileComponentLayout = new javax.swing.GroupLayout(profileComponent);
        profileComponent.setLayout(profileComponentLayout);
        profileComponentLayout.setHorizontalGroup(
            profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileComponentLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(update_btn)
                    .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel12)
                        .addComponent(jLabel10)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4)
                        .addGroup(profileComponentLayout.createSequentialGroup()
                            .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel19)
                                .addComponent(jLabel21))
                            .addGap(23, 23, 23)
                            .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label_student_dob, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                .addComponent(label_student_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_student_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_student_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_student_address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_student_phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_student_course, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel16)
                        .addGroup(profileComponentLayout.createSequentialGroup()
                            .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18)
                                .addComponent(jLabel20))
                            .addGap(26, 26, 26)
                            .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(student_newpass_field)
                                .addComponent(student_confirmpass_field)
                                .addComponent(student_oldpass_field, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(121, 121, 121))
        );
        profileComponentLayout.setVerticalGroup(
            profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileComponentLayout.createSequentialGroup()
                .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profileComponentLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2))
                    .addGroup(profileComponentLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(label_student_id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(label_student_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(label_student_address))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(label_student_phone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(label_student_email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(label_student_dob))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(label_student_course))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(student_oldpass_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(student_newpass_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(student_confirmpass_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(update_btn)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        Body.add(profileComponent, "card2");

        YearWiseModule.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Module");

        Enrolled_Btn.setBackground(new java.awt.Color(75, 75, 130));
        Enrolled_Btn.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        Enrolled_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Enrolled_Btn.setText("Enroll Modules");
        Enrolled_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enrolled_BtnActionPerformed(evt);
            }
        });

        enrolled_modules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Module_Id", "Module_Name"
            }
        ));
        jScrollPane1.setViewportView(enrolled_modules);

        javax.swing.GroupLayout YearWiseModuleLayout = new javax.swing.GroupLayout(YearWiseModule);
        YearWiseModule.setLayout(YearWiseModuleLayout);
        YearWiseModuleLayout.setHorizontalGroup(
            YearWiseModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YearWiseModuleLayout.createSequentialGroup()
                .addGroup(YearWiseModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(YearWiseModuleLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel8))
                    .addGroup(YearWiseModuleLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(YearWiseModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Enrolled_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        YearWiseModuleLayout.setVerticalGroup(
            YearWiseModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YearWiseModuleLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Enrolled_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Body.add(YearWiseModule, "card2");

        year1_component.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Year 1");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Module1");

        module1.setBackground(new java.awt.Color(255, 255, 255));
        module1.setForeground(new java.awt.Color(0, 0, 0));
        module1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                module1ActionPerformed(evt);
            }
        });

        module2.setBackground(new java.awt.Color(255, 255, 255));
        module2.setForeground(new java.awt.Color(0, 0, 0));
        module2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                module2ActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Module2");

        module3.setBackground(new java.awt.Color(255, 255, 255));
        module3.setForeground(new java.awt.Color(0, 0, 0));
        module3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                module3ActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Module3");

        module4.setBackground(new java.awt.Color(255, 255, 255));
        module4.setForeground(new java.awt.Color(0, 0, 0));
        module4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                module4ActionPerformed(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Module4");

        update_btn1.setBackground(new java.awt.Color(75, 75, 130));
        update_btn1.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        update_btn1.setForeground(new java.awt.Color(255, 255, 255));
        update_btn1.setText("Update");
        update_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btn1ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Year ");

        year_label.setBackground(new java.awt.Color(255, 255, 255));
        year_label.setForeground(new java.awt.Color(0, 0, 0));
        year_label.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year 1", "Year 2", "Year 3" }));
        year_label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year_labelActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Semester");

        sem_label.setBackground(new java.awt.Color(255, 255, 255));
        sem_label.setForeground(new java.awt.Color(0, 0, 0));
        sem_label.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem 1", "Sem 2" }));
        sem_label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem_labelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout year1_componentLayout = new javax.swing.GroupLayout(year1_component);
        year1_component.setLayout(year1_componentLayout);
        year1_componentLayout.setHorizontalGroup(
            year1_componentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(year1_componentLayout.createSequentialGroup()
                .addGroup(year1_componentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(year1_componentLayout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(update_btn1))
                    .addGroup(year1_componentLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(year_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(year1_componentLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(year1_componentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(year1_componentLayout.createSequentialGroup()
                                .addGroup(year1_componentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(year1_componentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(module4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(module2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(year1_componentLayout.createSequentialGroup()
                                .addGroup(year1_componentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(year1_componentLayout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(161, 161, 161)
                                        .addComponent(jLabel25)
                                        .addGap(45, 45, 45)
                                        .addComponent(sem_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11)
                                    .addGroup(year1_componentLayout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(module1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, year1_componentLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(module3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        year1_componentLayout.setVerticalGroup(
            year1_componentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(year1_componentLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(year1_componentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(year_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(sem_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(year1_componentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(year1_componentLayout.createSequentialGroup()
                        .addComponent(module1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(year1_componentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(module2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(year1_componentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(module3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(year1_componentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(module4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(update_btn1)
                .addContainerGap())
        );

        Body.add(year1_component, "card2");

        teacher_components.setBackground(new java.awt.Color(255, 255, 255));
        teacher_components.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teacher_list_table.setBackground(new java.awt.Color(182, 182, 221));
        teacher_list_table.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        teacher_list_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Teacher Id", "Teacher", "Module_Id", "Module_Name"
            }
        ));
        jScrollPane4.setViewportView(teacher_list_table);

        teacher_components.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 560, 390));

        jLabel27.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Teachers");
        teacher_components.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classroom (3).png"))); // NOI18N
        teacher_components.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        Body.add(teacher_components, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Body.removeAll();
        Body.add(YearWiseModule);
        Body.repaint();
        Body.revalidate();
        

        try{
            DefaultTableModel tableModel = (DefaultTableModel)enrolled_modules.getModel();
            tableModel.setRowCount(0); // clearing table data.
            Connection conn = checkConnection();
            prep_statement = conn.createStatement();
            
            prep = conn.prepareStatement("Select * from enrolled_module where Student_Id = '"+student_id+"'");
            execute_query = prep.executeQuery(); 
            
//            if(!execute_query.next()){
//                JOptionPane.showMessageDialog(this, "Error");
//                return;
//            }           
            

            while (execute_query.next()){
                String module_id = execute_query.getString("Module_Id");
                String module_name = execute_query.getString("Module_Name");


                String table_data[] = {module_id, module_name};
                tableModel.addRow(table_data);
                enrolled_modules.setEnabled(false);
            }

            return;
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        Body.removeAll();
        Body.add(profileComponent);
        Body.repaint();
        Body.revalidate();
        
        try{ 
           Connection conn = checkConnection(); 
           prep_statement = conn.createStatement();
           execute_query  = prep_statement.executeQuery("Select * from student where Student_Id = '"+student_id+"'");
           if (execute_query.next()) {
               String s_id = execute_query.getString("Student_Id");
               String s_first_name = execute_query.getString("First_Name");
               String s_middle_name = execute_query.getString("Middle_Name");
               String s_last_name = execute_query.getString("Last_Name");
               String s_name = s_first_name + " " + s_middle_name +  " " + s_last_name;
               String s_address = execute_query.getString("Address");
               String s_phone = execute_query.getString("Phone");
               String s_email = execute_query.getString("Email");
               String s_dob = execute_query.getString("DOB");
               String course = execute_query.getString("Course");
               
               label_student_id.setText(s_id);
               label_student_name.setText(s_name);
               label_student_address.setText(s_address);
               label_student_phone.setText(s_phone);
               label_student_email.setText(s_email);
               label_student_dob.setText(s_dob);
               label_student_course.setText(course);
           } 
        }catch (Exception ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_profileActionPerformed

    private void ResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultActionPerformed

    private void teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherActionPerformed
       Body.removeAll();
        Body.add(teacher_components);
        Body.repaint();
        Body.revalidate();
        
        DefaultTableModel tableModel = (DefaultTableModel)teacher_list_table.getModel();
        tableModel.setRowCount(0); // clearing table data.

        try{
            Connection conn = checkConnection();
            prep_statement = conn.createStatement();
            
            prep = conn.prepareStatement("Select * from student where Student_Id = '"+student_id+"'");
            execute_query = prep.executeQuery(); 
            
            if(!execute_query.next()){
                JOptionPane.showMessageDialog(this, "Error");
                return;
            }
            String course_name = execute_query.getString("Course");
            
            prep = conn.prepareStatement("Select * from courses where CourseName = '"+course_name+"'");
            execute_query = prep.executeQuery(); 
            
            if(!execute_query.next()){
                JOptionPane.showMessageDialog(this, "Error");
                return;
            }
            String course_id = execute_query.getString("Course_Id");
            
            prep = conn.prepareStatement("Select * from teacher_module where Course_Id = '"+course_id+"'");
            execute_query = prep.executeQuery(); 
            
            if(!execute_query.next()){
                JOptionPane.showMessageDialog(this, "Error");
                return;
            }
            
            
            while (execute_query.next()){
                String t_id = execute_query.getString("Teacher_Id");
                String t_name = execute_query.getString("Teacher_Name");
                String module_id = execute_query.getString("Module_Id");
                String module_name = execute_query.getString("Module_Name");

                String table_data[] = {t_id, t_name, module_id, module_name};
                tableModel.addRow(table_data);
                teacher_list_table.setEnabled(false);
            }

            return;
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_teacherActionPerformed

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
        dispose();
        Login lgn = new Login();
        lgn.setVisible(true);

    }//GEN-LAST:event_logout1ActionPerformed

    private void student_newpass_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_newpass_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_newpass_fieldActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
       try {
           Connection conn = checkConnection();
           prep_statement = conn.createStatement();
           String s_old_password = String.valueOf(student_oldpass_field.getPassword());
           String s_new_password = String.valueOf(student_newpass_field.getPassword());
           String s_confirm_password = String.valueOf(student_confirmpass_field.getPassword());
           execute_query = prep_statement.executeQuery("Select * from student where Student_Id = '"+student_id+"'");
           
           if (execute_query.next()) {
               String store_password = execute_query.getString("Password");
               
               if (store_password.equals(s_old_password)){
                   if (s_new_password.equals(s_confirm_password)){
                       prep_statement.executeUpdate("update student set Password = '"+ s_new_password +"' where Student_Id = '"+student_id+"'");
                       JOptionPane.showMessageDialog(this, "Password Updated Sucessfully");
                   } else {
                       JOptionPane.showMessageDialog(this, "Password does not match!");
                   }
               } else {
                   JOptionPane.showMessageDialog(this, "Old password does not match!");
               }
           }
           
       } catch(Exception ex) {
           System.out.println(ex);
       }
    }//GEN-LAST:event_update_btnActionPerformed

    private void student_oldpass_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_oldpass_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_oldpass_fieldActionPerformed

    private void Enrolled_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enrolled_BtnActionPerformed
        Body.removeAll();
        Body.add(year1_component);
        Body.repaint();
        Body.revalidate();
        
        
    }//GEN-LAST:event_Enrolled_BtnActionPerformed

    private void module1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_module1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_module1ActionPerformed

    private void module2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_module2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_module2ActionPerformed

    private void module3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_module3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_module3ActionPerformed

    private void module4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_module4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_module4ActionPerformed

    private void update_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btn1ActionPerformed
        try{   
            String year = year_label.getSelectedItem().toString();
            String sem = sem_label.getSelectedItem().toString();
            String moduleA = module1.getSelectedItem().toString();
            String moduleB = module2.getSelectedItem().toString();
            String moduleC = module3.getSelectedItem().toString();
            String moduleD = module4.getSelectedItem().toString();


            if (moduleA.equals(moduleB) || moduleA.equals(moduleC) || moduleA.equals(moduleD) || moduleB.equals(moduleC) ||  moduleB.equals(moduleD) || moduleC.equals(moduleD) ) {
                JOptionPane.showMessageDialog(this, "Modules cannot be repeated", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            

            Connection conn = checkConnection();
            
            ArrayList<String> module_list1 = new ArrayList<String>();
            module_list1.add(moduleA);
            module_list1.add(moduleB);
            module_list1.add(moduleC);
            module_list1.add(moduleD);

            for(String module: module_list1) {
                prep = conn.prepareStatement("Select * from enrolled_module where module_name = '"+module+"' and Student_Id= '"+student_id+"'");
                execute_query = prep.executeQuery();

                if(execute_query.next()){
                    JOptionPane.showMessageDialog(this, "Data already exist");
                    return;
                }
               

                prep = conn.prepareStatement("Select * from module where module = '"+module+"'");
                execute_query = prep.executeQuery();

                if(!execute_query.next()){
                    JOptionPane.showMessageDialog(this, "Error", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                String course_id = execute_query.getString("Course_Id");
                String module_id =execute_query.getString("module_id");
                
                prep = conn.prepareStatement("Select * from student where Student_Id = '"+student_id+"'");
                execute_query = prep.executeQuery();

                if(!execute_query.next()){
                    JOptionPane.showMessageDialog(this, "Error", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                String student_id = execute_query.getString("student_id");
                String first_name =execute_query.getString("First_Name");
                String middle_name =execute_query.getString("Middle_Name");
                String last_name =execute_query.getString("Last_Name");
                String full_student_name = first_name + " "+middle_name+" "+ last_name;

                prep  = conn.prepareStatement("Insert into enrolled_module(Student_Id, Student_Name, Course_Id, Module_Id, Module_Name) values (?, ?, ?, ?, ?)");
                prep.setString(1, student_id);
                prep.setString(2, full_student_name);
                prep.setString(3, course_id);
                prep.setString(4, module_id);
                prep.setString(5, module);


                int row = prep.executeUpdate();
                System.out.println(row);
                

            }
            JOptionPane.showMessageDialog(this, "Updated Successfully.");

        } catch (Exception ex) {
            System.out.println(ex);
        }
        
        
    }//GEN-LAST:event_update_btn1ActionPerformed

    private void year_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year_labelActionPerformed
        

        try {
            
            String year = year_label.getSelectedItem().toString();
            String sem = sem_label.getSelectedItem().toString();
                        
            Connection conn = checkConnection();
            
            prep = conn.prepareStatement("Select * from student where Student_Id = '"+student_id+"'");
            execute_query = prep.executeQuery(); 
            
            if(!execute_query.next()){
                JOptionPane.showMessageDialog(this, "Error");
                return;
            }
            String course_name = execute_query.getString("Course");

         prep = conn.prepareStatement("Select * from courses where CourseName = '"+course_name+"' ");
            execute_query = prep.executeQuery(); 
            
            if(!execute_query.next()){
                JOptionPane.showMessageDialog(this, "Error");
                return;
            }
            String course_id = execute_query.getString("Course_Id");
            
            if (year == "Year 3"){
                prep_statement = conn.createStatement();
                execute_query = prep_statement.executeQuery("select * from module where year = '"+year+"' and sem='"+sem+"' and Course_Id='"+course_id+"' and Optional = 'No'");
                   
                
                module1.removeAllItems();
                module2.removeAllItems();
                module3.removeAllItems();
                module4.removeAllItems();

                while (execute_query.next()) {
                    String tempVar = execute_query.getString("module");
                    module1.addItem(tempVar);
                    module2.addItem(tempVar);
                }
                    
                    
                prep_statement = conn.createStatement();
                execute_query = prep_statement.executeQuery("select * from module where year = '"+year+"' and sem='"+sem+"' and Course_Id='"+course_id+"' and Optional = 'Yes'");

                while (execute_query.next()) {
                    String tempVar1 = execute_query.getString("module");
                    module3.addItem(tempVar1);
                    module4.addItem(tempVar1);
                }

            } else {
                prep_statement = conn.createStatement();
                execute_query = prep_statement.executeQuery("select * from module where year = '"+year+"' and sem='"+sem+"' and Course_Id='"+course_id+"'");
                
                module1.removeAllItems();
                module2.removeAllItems();
                module3.removeAllItems();
                module4.removeAllItems();

                while (execute_query.next()) {
                    String tempVar = execute_query.getString("module");
                    module1.addItem(tempVar);
                    module2.addItem(tempVar);
                    module3.addItem(tempVar);
                    module4.addItem(tempVar);

                }                
            }
            

        } catch (Exception exp) {
            System.out.println(exp);
        }
    }//GEN-LAST:event_year_labelActionPerformed

    private void sem_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem_labelActionPerformed
        try {
            
            String year = year_label.getSelectedItem().toString();
            String sem = sem_label.getSelectedItem().toString();
                        
            Connection conn = checkConnection();
            
            prep = conn.prepareStatement("Select * from student where Student_Id = '"+student_id+"'");
            execute_query = prep.executeQuery(); 
            
            if(!execute_query.next()){
                JOptionPane.showMessageDialog(this, "Error");
                return;
            }
            String course_name = execute_query.getString("Course");
            
            prep = conn.prepareStatement("Select * from courses where CourseName = '"+course_name+"' ");
            execute_query = prep.executeQuery(); 
            
            if(!execute_query.next()){
                JOptionPane.showMessageDialog(this, "Error");
                return;
            }
            String course_id = execute_query.getString("Course_Id");
            
            if (year == "Year 3"){
                prep_statement = conn.createStatement();
                execute_query = prep_statement.executeQuery("select * from module where year = '"+year+"' and sem='"+sem+"' and Course_Id='"+course_id+"' and Optional = 'No'");
                   
                
                module1.removeAllItems();
                module2.removeAllItems();
                module3.removeAllItems();
                module4.removeAllItems();

                while (execute_query.next()) {
                    String tempVar = execute_query.getString("module");
                    module1.addItem(tempVar);
                    module2.addItem(tempVar);
                }
                    
                    
                prep_statement = conn.createStatement();
                execute_query = prep_statement.executeQuery("select * from module where year = '"+year+"' and sem='"+sem+"' and Course_Id='"+course_id+"' and Optional = 'Yes'");

                while (execute_query.next()) {
                    String tempVar1 = execute_query.getString("module");
                    module3.addItem(tempVar1);
                    module4.addItem(tempVar1);
                }

            } else {
                prep_statement = conn.createStatement();
                execute_query = prep_statement.executeQuery("select * from module where year = '"+year+"' and sem='"+sem+"' and Course_Id='"+course_id+"'");
                
                module1.removeAllItems();
                module2.removeAllItems();
                module3.removeAllItems();
                module4.removeAllItems();

                while (execute_query.next()) {
                    String tempVar = execute_query.getString("module");
                    module1.addItem(tempVar);
                    module2.addItem(tempVar);
                    module3.addItem(tempVar);
                    module4.addItem(tempVar);

                }                
            }
            

        } catch (Exception exp) {
            System.out.println(exp);
        }
    }//GEN-LAST:event_sem_labelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_portal("Null").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JButton Enrolled_Btn;
    private javax.swing.JButton Result;
    private javax.swing.JPanel YearWiseModule;
    private javax.swing.JTable enrolled_modules;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private java.awt.Label label1;
    private javax.swing.JLabel label_student_address;
    private javax.swing.JLabel label_student_course;
    private javax.swing.JLabel label_student_dob;
    private javax.swing.JLabel label_student_email;
    private javax.swing.JLabel label_student_id;
    private javax.swing.JLabel label_student_name;
    private javax.swing.JLabel label_student_phone;
    private javax.swing.JButton logout1;
    private javax.swing.JComboBox<String> module1;
    private javax.swing.JComboBox<String> module2;
    private javax.swing.JComboBox<String> module3;
    private javax.swing.JComboBox<String> module4;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JButton profile;
    private javax.swing.JPanel profileComponent;
    private javax.swing.JComboBox<String> sem_label;
    private javax.swing.JPasswordField student_confirmpass_field;
    private javax.swing.JPasswordField student_newpass_field;
    private javax.swing.JPasswordField student_oldpass_field;
    private javax.swing.JButton teacher;
    private javax.swing.JPanel teacher_components;
    private javax.swing.JTable teacher_list_table;
    private javax.swing.JButton update_btn;
    private javax.swing.JButton update_btn1;
    private javax.swing.JPanel year1_component;
    private javax.swing.JComboBox<String> year_label;
    // End of variables declaration//GEN-END:variables
}
