
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class teacher_portal extends javax.swing.JFrame {
    Statement prep_statement;
    PreparedStatement prep_state;
    ResultSet execute_query;
    String userID;


   
    /**
     * Creates new form Registration
     */
    public teacher_portal(String ID) {
        initComponents();
        this.userID = ID;
        
    }
    
    public Connection checkConnection() {
        db database = new db();
        Connection conn = database.checkConnection();
        return conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        view_all_btn2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Header_dashboard = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        Dashboard = new javax.swing.JButton();
        Courses = new javax.swing.JButton();
        Student = new javax.swing.JButton();
        teacher = new javax.swing.JButton();
        logout1 = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        Body = new javax.swing.JPanel();
        dashbaord = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        profileComponent = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        label_TeacherID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_Name_Teacher = new javax.swing.JLabel();
        label_address = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        label_phone = new javax.swing.JLabel();
        label_dob = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        confirmpass_field = new javax.swing.JPasswordField();
        newpass_field = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        update_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        oldpass_field = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        Module_List = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_module_teacher = new javax.swing.JTable();
        view_all_btn_course = new javax.swing.JButton();
        teacher_components = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        teacher_list_table = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        teacher_name_insert = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        view_all_btn1 = new javax.swing.JButton();
        student_components = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        student_list_table = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        search_button1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        modulename_ComboBox = new javax.swing.JComboBox<>();
        Update_button = new javax.swing.JButton();

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList2);

        view_all_btn2.setBackground(new java.awt.Color(75, 75, 130));
        view_all_btn2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        view_all_btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye.png"))); // NOI18N
        view_all_btn2.setText("View All");
        view_all_btn2.setBorder(null);
        view_all_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_all_btn2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1054, 574));

        Header_dashboard.setBackground(new java.awt.Color(75, 75, 130));
        Header_dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Course Management System");
        Header_dashboard.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 165, 278, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentdashboard.png"))); // NOI18N
        Header_dashboard.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 18, -1, -1));

        Dashboard.setBackground(new java.awt.Color(75, 75, 130));
        Dashboard.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png"))); // NOI18N
        Dashboard.setText("Dashboard");
        Dashboard.setBorder(null);
        Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardActionPerformed(evt);
            }
        });
        Header_dashboard.add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 207, 193, 41));

        Courses.setBackground(new java.awt.Color(75, 75, 130));
        Courses.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        Courses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cubes.png"))); // NOI18N
        Courses.setText("     Module");
        Courses.setBorder(null);
        Courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoursesActionPerformed(evt);
            }
        });
        Header_dashboard.add(Courses, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 301, 193, 41));

        Student.setBackground(new java.awt.Color(75, 75, 130));
        Student.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        Student.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graduated.png"))); // NOI18N
        Student.setText("    Student");
        Student.setBorder(null);
        Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentActionPerformed(evt);
            }
        });
        Header_dashboard.add(Student, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 348, 193, 41));

        teacher.setBackground(new java.awt.Color(75, 75, 130));
        teacher.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        teacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teacher.png"))); // NOI18N
        teacher.setText("    Teacher");
        teacher.setBorder(null);
        teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherActionPerformed(evt);
            }
        });
        Header_dashboard.add(teacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 395, 193, 41));

        logout1.setBackground(new java.awt.Color(75, 75, 130));
        logout1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        logout1.setText("    Logout");
        logout1.setBorder(null);
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });
        Header_dashboard.add(logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 193, 41));

        profile.setBackground(new java.awt.Color(75, 75, 130));
        profile.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        profile.setText("     Profile");
        profile.setBorder(null);
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        Header_dashboard.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 254, 193, 41));

        Body.setBackground(new java.awt.Color(255, 255, 255));
        Body.setLayout(new java.awt.CardLayout());

        dashbaord.setBackground(new java.awt.Color(255, 255, 255));
        dashbaord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Management System");
        dashbaord.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 900, 90));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("to Course ");
        dashbaord.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 280, 900, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/welcome-back.png"))); // NOI18N
        dashbaord.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        Body.add(dashbaord, "card2");

        profileComponent.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Profile");

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Id");

        label_email.setBackground(new java.awt.Color(255, 255, 255));
        label_email.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_email.setForeground(new java.awt.Color(0, 0, 0));
        label_email.setText("jLabel5");

        label_TeacherID.setBackground(new java.awt.Color(255, 255, 255));
        label_TeacherID.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_TeacherID.setForeground(new java.awt.Color(0, 0, 0));
        label_TeacherID.setText("jLabel5");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Email");

        label_Name_Teacher.setBackground(new java.awt.Color(255, 255, 255));
        label_Name_Teacher.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_Name_Teacher.setForeground(new java.awt.Color(0, 0, 0));
        label_Name_Teacher.setText("jLabel5");

        label_address.setBackground(new java.awt.Color(255, 255, 255));
        label_address.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_address.setForeground(new java.awt.Color(0, 0, 0));
        label_address.setText("jLabel5");

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Phone");

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Address");

        label_phone.setBackground(new java.awt.Color(255, 255, 255));
        label_phone.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_phone.setForeground(new java.awt.Color(0, 0, 0));
        label_phone.setText("jLabel5");

        label_dob.setBackground(new java.awt.Color(255, 255, 255));
        label_dob.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_dob.setForeground(new java.awt.Color(0, 0, 0));
        label_dob.setText("jLabel5");

        jLabel19.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("DOB");

        jLabel16.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Password");

        jLabel17.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("New Password");

        confirmpass_field.setBackground(new java.awt.Color(255, 255, 255));
        confirmpass_field.setForeground(new java.awt.Color(0, 0, 0));
        confirmpass_field.setText("jPasswordField1");

        newpass_field.setBackground(new java.awt.Color(255, 255, 255));
        newpass_field.setForeground(new java.awt.Color(0, 0, 0));
        newpass_field.setText("jPasswordField1");
        newpass_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpass_fieldActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Confirm Password");

        update_btn.setBackground(new java.awt.Color(75, 75, 130));
        update_btn.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        update_btn.setForeground(new java.awt.Color(255, 255, 255));
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N

        oldpass_field.setBackground(new java.awt.Color(255, 255, 255));
        oldpass_field.setForeground(new java.awt.Color(0, 0, 0));
        oldpass_field.setText("jPasswordField1");
        oldpass_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldpass_fieldActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Old Password");

        javax.swing.GroupLayout profileComponentLayout = new javax.swing.GroupLayout(profileComponent);
        profileComponent.setLayout(profileComponentLayout);
        profileComponentLayout.setHorizontalGroup(
            profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileComponentLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addComponent(jLabel12)
                        .addComponent(jLabel10)
                        .addComponent(jLabel6)
                        .addGroup(profileComponentLayout.createSequentialGroup()
                            .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel19))
                            .addGap(50, 50, 50)
                            .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label_dob, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                .addComponent(label_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_TeacherID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_Name_Teacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel16)
                        .addGroup(profileComponentLayout.createSequentialGroup()
                            .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18)
                                .addComponent(jLabel20))
                            .addGap(26, 26, 26)
                            .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(newpass_field)
                                .addComponent(confirmpass_field)
                                .addComponent(oldpass_field, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                        .addComponent(jLabel4))
                    .addComponent(update_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(121, 121, 121))
        );
        profileComponentLayout.setVerticalGroup(
            profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileComponentLayout.createSequentialGroup()
                .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profileComponentLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2))
                    .addGroup(profileComponentLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(label_TeacherID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(label_Name_Teacher))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(label_address))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(label_phone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(label_email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(label_dob))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oldpass_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(newpass_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(confirmpass_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(update_btn)))
                .addGap(44, 125, Short.MAX_VALUE))
        );

        Body.add(profileComponent, "card2");

        Module_List.setBackground(new java.awt.Color(255, 255, 255));
        Module_List.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Module");
        Module_List.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 35, -1, -1));

        table_module_teacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Module Id", "Module Name"
            }
        ));
        jScrollPane5.setViewportView(table_module_teacher);

        Module_List.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 650, 300));

        view_all_btn_course.setBackground(new java.awt.Color(75, 75, 130));
        view_all_btn_course.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        view_all_btn_course.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye.png"))); // NOI18N
        view_all_btn_course.setText("View All");
        view_all_btn_course.setBorder(null);
        view_all_btn_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_all_btn_courseActionPerformed(evt);
            }
        });
        Module_List.add(view_all_btn_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, 41));

        Body.add(Module_List, "card2");

        teacher_components.setBackground(new java.awt.Color(255, 255, 255));
        teacher_components.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teacher_list_table.setBackground(new java.awt.Color(182, 182, 221));
        teacher_list_table.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        teacher_list_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Teacher Id", "Teacher", "Phone No.", "Email"
            }
        ));
        jScrollPane3.setViewportView(teacher_list_table);

        teacher_components.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 830, 350));

        jLabel27.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Teachers");
        teacher_components.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Enter first name only");
        teacher_components.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        teacher_name_insert.setBackground(new java.awt.Color(255, 255, 255));
        teacher_name_insert.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        teacher_name_insert.setForeground(new java.awt.Color(0, 0, 0));
        teacher_name_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacher_name_insertActionPerformed(evt);
            }
        });
        teacher_components.add(teacher_name_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 320, 40));

        search_button.setBackground(new java.awt.Color(75, 75, 130));
        search_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });
        teacher_components.add(search_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, 40));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Teachers Name");
        teacher_components.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        view_all_btn1.setBackground(new java.awt.Color(75, 75, 130));
        view_all_btn1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        view_all_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye.png"))); // NOI18N
        view_all_btn1.setText("View All");
        view_all_btn1.setBorder(null);
        view_all_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_all_btn1ActionPerformed(evt);
            }
        });
        teacher_components.add(view_all_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 110, 41));

        Body.add(teacher_components, "card2");

        student_components.setBackground(new java.awt.Color(255, 255, 255));
        student_components.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        student_list_table.setBackground(new java.awt.Color(182, 182, 221));
        student_list_table.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        student_list_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student Id", "Student Name", "Module_ID", "Module_Name", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        student_list_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                student_list_tableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(student_list_table);

        student_components.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 830, 320));

        jLabel28.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Students");
        student_components.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        search_button1.setBackground(new java.awt.Color(75, 75, 130));
        search_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        search_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_button1ActionPerformed(evt);
            }
        });
        student_components.add(search_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, 40));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Module Name");
        student_components.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        modulename_ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        modulename_ComboBox.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        modulename_ComboBox.setForeground(new java.awt.Color(0, 0, 0));
        student_components.add(modulename_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 320, 40));

        Update_button.setBackground(new java.awt.Color(75, 75, 130));
        Update_button.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        Update_button.setForeground(new java.awt.Color(255, 255, 255));
        Update_button.setText("Update");
        Update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_buttonActionPerformed(evt);
            }
        });
        student_components.add(Update_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, -1, -1));

        Body.add(student_components, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardActionPerformed
        Body.removeAll();
        Body.add(dashbaord);
        Body.repaint();
        Body.revalidate();
    }//GEN-LAST:event_DashboardActionPerformed

    private void CoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoursesActionPerformed
        Body.removeAll();
        Body.add(Module_List);
        Body.repaint();
        Body.revalidate();
        
        
    }//GEN-LAST:event_CoursesActionPerformed

    private void StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentActionPerformed
        Body.removeAll();
        Body.add(student_components);
        Body.repaint();
        Body.revalidate();
        
        try {
            
            Connection conn = checkConnection();
            
            prep_state = conn.prepareStatement("Select * from teacher_module where Teacher_Id = '"+userID+"'");
            execute_query = prep_state.executeQuery(); 
            
            if(!execute_query.next()){
                JOptionPane.showMessageDialog(this, "Error");
                return;
            }
            
            while (execute_query.next()) {
                    String tempVar = execute_query.getString("Module_Name");
                    modulename_ComboBox.addItem(tempVar);

            }
            
            

        } catch (Exception exp) {
            System.out.println(exp);
        }
    }//GEN-LAST:event_StudentActionPerformed

    private void teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherActionPerformed
        Body.removeAll();
        Body.add(teacher_components);
        Body.repaint();
        Body.revalidate();

        DefaultTableModel tableModel = (DefaultTableModel)teacher_list_table.getModel();
        tableModel.setRowCount(0); // clearing table data.
        
        try{ 
            Connection conn = checkConnection(); 
            
            prep_statement = conn.createStatement();
            
            
            prep_statement = conn.createStatement();
            execute_query = prep_statement.executeQuery("Select * from teacher");
            
            
            while (execute_query.next()){
                String teacher_id = execute_query.getString("Teacher_Id");
                String t_f_name = execute_query.getString("First_Name");
                String t_m_name = execute_query.getString("Middle_Name");
                String t_l_name = execute_query.getString("Last_Name");
                String t_name = t_f_name + " " + t_m_name + " "+ t_l_name;
                String t_phone = execute_query.getString("Phone");
                String t_email = execute_query.getString("Email");
                
                String table_data[] = {teacher_id, t_name, t_phone, t_email};
                tableModel.addRow(table_data);
                teacher_list_table.setEnabled(false);
            }

            
            return;
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_teacherActionPerformed

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
       dispose();
       Login lgn = new Login();
       lgn.setVisible(true);
        
    }//GEN-LAST:event_logout1ActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        Body.removeAll();
        Body.add(profileComponent);
        Body.repaint();
        Body.revalidate();
        
        try{ 
           Connection conn = checkConnection(); 
           prep_statement = conn.createStatement();
           execute_query  = prep_statement.executeQuery("Select * from teacher where Teacher_Id = '"+userID+"'");
           if (execute_query.next()) {
               String t_id = execute_query.getString("Teacher_Id");
               String t_first_name = execute_query.getString("First_Name");
               String t_middle_name = execute_query.getString("Middle_Name");
               String t_last_name = execute_query.getString("Last_Name");
               String t_name = t_first_name + " " + t_middle_name +  " " + t_last_name;
               String t_address = execute_query.getString("Address");
               String t_phone = execute_query.getString("Phone");
               String t_email = execute_query.getString("Email");
               String t_dob = execute_query.getString("DOB");
               
               label_TeacherID.setText(t_id);
               label_Name_Teacher.setText(t_name);
               label_address.setText(t_address);
               label_phone.setText(t_phone);
               label_email.setText(t_email);
               label_dob.setText(t_dob);
           } 
        }catch (Exception ex) {
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_profileActionPerformed

    private void newpass_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpass_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpass_fieldActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        try{ 
           Connection conn = checkConnection();
           prep_statement = conn.createStatement();
           String oldPass = String.valueOf(oldpass_field.getPassword());
           String newPass = String.valueOf(newpass_field.getPassword());
           String confirmPass = String.valueOf(confirmpass_field.getPassword());
           execute_query = prep_statement.executeQuery("select Teacher_Id, Password from teacher where Teacher_Id = '"+userID+"'");
           if (execute_query.next()) {
               String storePassVal = execute_query.getString("Password");
               if (oldPass.equals(storePassVal)) {
                    if (newPass.equals(confirmPass)) {
                        prep_statement.executeUpdate("update teacher set Password = '"+ newPass +"' where Teacher_Id = '"+userID+"'");
                        JOptionPane.showMessageDialog(this, "Password Updated Sucessfully");
                        return;
                    } else {
                        JOptionPane.showMessageDialog(this, "Password does not match!");
                        return;
                    }
               } else {
                   JOptionPane.showMessageDialog(this, "Old password does not match!");
                   return;
               }
           }
        }catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_update_btnActionPerformed

    private void oldpass_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldpass_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldpass_fieldActionPerformed

    private void teacher_name_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacher_name_insertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacher_name_insertActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed

        try{
            Connection conn = checkConnection();
            prep_statement = conn.createStatement();
            String teacher_name_label = teacher_name_insert.getText();
            DefaultTableModel tableModel = (DefaultTableModel)teacher_list_table.getModel();
            tableModel.setRowCount(0); // clearing table data.

            execute_query = prep_statement.executeQuery("select * from teacher where first_name = '"+teacher_name_label+"'");

            
            
            while (execute_query.next()){
                String teacher_id = execute_query.getString("Teacher_Id");
                String t_f_name = execute_query.getString("First_Name");
                String t_m_name = execute_query.getString("Middle_Name");
                String t_l_name = execute_query.getString("Last_Name");
                String t_name = t_f_name + " " + t_m_name + " "+ t_l_name;
                String t_phone = execute_query.getString("Phone");
                String t_email = execute_query.getString("Email");

                String table_data[] = {teacher_id, t_name, t_phone, t_email};
                tableModel.addRow(table_data);
                teacher_list_table.setEnabled(false);

            }
        }catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_search_buttonActionPerformed

    private void view_all_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_all_btn1ActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel)teacher_list_table.getModel();
        tableModel.setRowCount(0); // clearing table data.
        
        try{ 
            Connection conn = checkConnection(); 
            prep_statement = conn.createStatement();
            execute_query = prep_statement.executeQuery("Select * from teacher");
            
            
            while (execute_query.next()){
                String teacher_id = execute_query.getString("Teacher_Id");
                String t_f_name = execute_query.getString("First_Name");
                String t_m_name = execute_query.getString("Middle_Name");
                String t_l_name = execute_query.getString("Last_Name");
                String t_name = t_f_name + " " + t_m_name + " "+ t_l_name;
                String t_phone = execute_query.getString("Phone");
                String t_email = execute_query.getString("Email");
                
                String table_data[] = {teacher_id, t_name, t_phone, t_email};
                tableModel.addRow(table_data);
                teacher_list_table.setEnabled(false);
            }

            

            
            return;
        } catch (Exception ex) {
            System.out.println(ex);
        }
        
        
    }//GEN-LAST:event_view_all_btn1ActionPerformed

    private void view_all_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_all_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view_all_btn2ActionPerformed

    private void view_all_btn_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_all_btn_courseActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel)table_module_teacher.getModel();
        tableModel.setRowCount(0); // clearing table data.
        
        try{ 
            Connection conn = checkConnection(); 
            
            prep_statement = conn.createStatement();
            execute_query = prep_statement.executeQuery("Select * from teacher where Teacher_id ='"+userID+"' ");
            
            if(!execute_query.next()) {
                JOptionPane.showMessageDialog(this, "Error");
            }
            
            String teacher_id = execute_query.getString("Teacher_Id");
            prep_statement = conn.createStatement();
            
            execute_query = prep_statement.executeQuery("Select * from teacher_module where Teacher_Id ='"+teacher_id+"' ");
            
            while (execute_query.next()){
                String module_id = execute_query.getString("Module_Id");
                String module_name = execute_query.getString("Module_Name");
                
                
                String table_data[] = {module_id, module_name};
                tableModel.addRow(table_data);
                table_module_teacher.setEnabled(false);
                
            }
            
        
            
            return;
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_view_all_btn_courseActionPerformed

    private void search_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_button1ActionPerformed
        String mod_name = modulename_ComboBox.getSelectedItem().toString();
        DefaultTableModel tableModel = (DefaultTableModel)student_list_table.getModel();
        tableModel.setRowCount(0); // clearing table data.
        
        
        try{ 
            Connection conn = checkConnection(); 
            
            prep_statement = conn.createStatement();
            execute_query = prep_statement.executeQuery("Select * from enrolled_module where Module_Name ='"+mod_name+"' ");

            while (execute_query.next()){
                String student_id = execute_query.getString("Student_Id");
                String student_name = execute_query.getString("Student_Name");
                String module_id = execute_query.getString("Module_Id");
                String module_name = execute_query.getString("Module_Name");
                String result = execute_query.getString("Marks");
                
                
                String table_data[] = {student_id, student_name, module_id, module_name,result};
                tableModel.addRow(table_data);
            
            }
            
            return;
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_search_button1ActionPerformed

    private void Update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_buttonActionPerformed
           
        try{
            DefaultTableModel tableModel = (DefaultTableModel)student_list_table.getModel();
            for (int i = 0; tableModel.getRowCount() > i; i++) {
                 String col1 = (String) tableModel.getValueAt(i, 0);
                String col2 = (String) tableModel.getValueAt(i, 1);
                String col3 = (String) tableModel.getValueAt(i, 2);
                 String col4 = (String) tableModel.getValueAt(i, 3);
                 
                 String col5 = (String) tableModel.getValueAt(i, 4);
                 markException mark = new markException(Integer.parseInt(col5));
                 mark.printException(col5, col1, col3);
                

//                System.out.println("Row: " + i + " Col 0: " + col1);
//                System.out.println("Row: " + i + " Col 1: " + col2);
//                System.out.println("Row: " + i + " Col 2: " + col3);
//                System.out.println("Row: " + i + " Col 3: " + col4);
//                System.out.println("Row: " + i + " Col 4: " + col5);
                
//                Connection conn = checkConnection(); 
            
//                prep_statement = conn.createStatement();
//                prep_statement.executeUpdate("Update enrolled_module SET Marks = '"+col5+"' where Student_Id= '"+col1+"' and Module_Id = '"+col3+"' ");
//    
            }
//        JOptionPane.showMessageDialog(this, "Result Updated."); 
            

        
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_Update_buttonActionPerformed

    private void student_list_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_student_list_tableMouseClicked
        
        DefaultTableModel tableModel = (DefaultTableModel)student_list_table.getModel();
        for (int i = 0; tableModel.getRowCount() > i; i++) {
             String col1 = (String) tableModel.getValueAt(i, 0);
             String col2 = (String) tableModel.getValueAt(i, 1);
             String col3 = (String) tableModel.getValueAt(i, 2);
             String col4 = (String) tableModel.getValueAt(i, 3);

//            System.out.println("Row: " + i + " Col 0: " + col1);
//            System.out.println("Row: " + i + " Col 1: " + col2);
//            System.out.println("Row: " + i + " Col 2: " + col3);
//            System.out.println("Row: " + i + " Col 3: " + col4);
        }
    }//GEN-LAST:event_student_list_tableMouseClicked

    
    public ArrayList<String> takecourse_name(){
        //This will collect all names from db
        ArrayList<String> course_names = new ArrayList<>();

        try{ 
            Connection conn = checkConnection(); 
            prep_statement = conn.createStatement();
            execute_query = prep_statement.executeQuery("Select * from courses");
            
            while (execute_query.next()){
                String c_name = execute_query.getString("CourseName");
                course_names.add(c_name);
            }
            

            
           
        } catch (Exception ex) {
            System.out.println(ex);
        }
         return course_names;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacher_portal("null").setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JButton Courses;
    private javax.swing.JButton Dashboard;
    private javax.swing.JPanel Header_dashboard;
    private javax.swing.JPanel Module_List;
    private javax.swing.JButton Student;
    private javax.swing.JButton Update_button;
    private javax.swing.JPasswordField confirmpass_field;
    private javax.swing.JPanel dashbaord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable2;
    private java.awt.Label label1;
    private javax.swing.JLabel label_Name_Teacher;
    private javax.swing.JLabel label_TeacherID;
    private javax.swing.JLabel label_address;
    private javax.swing.JLabel label_dob;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_phone;
    private javax.swing.JButton logout1;
    private javax.swing.JComboBox<String> modulename_ComboBox;
    private javax.swing.JPasswordField newpass_field;
    private javax.swing.JPasswordField oldpass_field;
    private javax.swing.JButton profile;
    private javax.swing.JPanel profileComponent;
    private javax.swing.JButton search_button;
    private javax.swing.JButton search_button1;
    private javax.swing.JPanel student_components;
    private javax.swing.JTable student_list_table;
    private javax.swing.JTable table_module_teacher;
    private javax.swing.JButton teacher;
    private javax.swing.JPanel teacher_components;
    private javax.swing.JTable teacher_list_table;
    private javax.swing.JTextField teacher_name_insert;
    private javax.swing.JButton update_btn;
    private javax.swing.JButton view_all_btn1;
    private javax.swing.JButton view_all_btn2;
    private javax.swing.JButton view_all_btn_course;
    // End of variables declaration//GEN-END:variables
}
